### ISSUE TITLE
Customize serialization to allow serialization/deserlaization of interfaces/abstract classes

### ISSUE THREAD

**Issue by darbio** [sapiens/DominoEventStore#1]
At the moment, when you use the in memory provider with a property that is an interface, or a class that is abstract, deserialization will fail. This is because Newtonsoft JSON does not understand what type to deserialize the property/class to.

> Could not create an instance of type Siren.Core.Domain.Shared.IIdentity. Type is an interface or abstract class and cannot be instantiated. Path 'EventId'.) ---> Newtonsoft.Json.JsonSerializationException: Could not create an instance of type Siren.Core.Domain.Shared.IIdentity. Type is an interface or abstract class and cannot be instantiated. Path 'EventId'.

Is there a way to customize the serialization of the object using the available `Newtonsoft.Json.JsonSerializer` options? (TypeNameHandling).

`TypeNameHandling = TypeNameHandling.All`

**Comment by sapiens** [comment]
It's by design. I need that data to be artifact free, i.e simple JSON . Now, why would you use an interface or a class that is abstract for an event? An event is **always**  a simple data structure

**Comment by sapiens** [comment]
Are you talking about snapshot serialization? I might have gotten the wrong impression.

**Comment by darbio** [comment]
No I was talking about event serialization. I agree that they should be simple objects, however an event should be able to have something similar to the following:

```
public interface IIdentity { }

public struct Identity<T>: IIdentity {
    private readonly int _value;

    public Id(int value) {
        this._value = value;
    }

    public static implicit operator int(Id<T> id) {
        return id._value;
    }

    public static explicit operator Id<T>(int value) {
        return new Id<T>(value);
    }
}

public class DomainEvent<T> {
    public IIdentity AggregateId { get; }
    ...
}

```

I can get around this by setting `DomainEvent.Id` to be an `int` but it's not very consistent with my domain model, which uses the strongly typed Id.

**Comment by sapiens** [comment]
This is where I pull the 'opinionated' card. Based on my experience, your approach is kinda complicated.  A domain event is a _simple_ data structure having only primitives. That's because an event in the end is just a message, a DTO.

So, I'll have to insist on things to remain how they are for now. 

P.S: All my aggregate ids are guids. I see no utility in being them more.

**Comment by darbio** [comment]
That's cool, your framework, your rules (and I totally respect your opinions) 👍.

I partially agree about guids - my aggregate id's _usually_ are guids, however I don't agree that they always _need_ to be guids. From experience, sometimes it makes sense for an aggregate id to be something else, e.g.: ISBN when storing books or serial number when storing parts.

I don't agree that events should only contain primitives and I'm not sure where the logic that a domain event containing only primitives comes from. For example, what is wrong with the following?

```
public class CreatedDomainEventArgs {
    public string FirstName { get; }
    public string LastName { get; }
}

public class CreatedDomainEvent : DomainEvent {
    public Guid AggregateId { get; }
    public CreatedDomainEventArgs Args { get; }
    
    public CreatedDomainEvent(CreatedDomainEventArgs args) {
        this.Args = args;
    }

    ...
}
```

Just as in DTO's, this doesn't appear to make anything more complicated, and in fact potentially makes the code more readable.

**FWIW, this framework doesn't stop you from doing this - the above is purely a question on why events should only contain primitives. Maybe I have missed something...**

**Comment by darbio** [comment]
> While an aggregate usually has a natural id , it's always best for that implementation to have a 'technical' id which usually is a guid, but can be anything you want.

Interesting concept. Do you have an example of how you implement this?
